### ISSUE TITLE
Outdated bio on profile

### ISSUE THREAD

**Issue by stepva** [jdjfisher/jdjfisher#1]
Literally unusable, has "Student at the University of Warwick" but that is an old version and needs to be updated. Thanks!

**Comment by jdjfisher** [comment]
Thanks for opening your first issue here! Be sure to follow the issue template!

**Comment by stepva** [comment]
My apologies, I hope this will do. There is no ISSUE_TEMPLATE.md in this repository (which should probably be a separate issue tbh)...

### Subject of the issue
Outdated profile bio that should be updated

### Your environment
* Brave V1.31.88 (Oct 29, 2021)
* macOS Mojave V10.14.6
* MacBook Air (13-inch, 2017)

### Steps to reproduce
Open your browser, go to [https://github.com/jdjfisher](https://github.com/jdjfisher) and look at the profile bio on the left side, below the Follow button.

### Expected behaviour
The profile bio should be something like 
"Web Developer at YourHippo | University of Warwick graduate"

### Actual behaviour
Profile bio reads "Web Developer | Student at the University of Warwick", however that is no longer true as the profile owner is, in fact, not a student anymore.

**Comment by stepva** [comment]
lgtm, thanks for the new version
